# Generated by Django 4.2.9 on 2024-01-31 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_description', models.CharField(max_length=256)),
                ('task_priority', models.CharField(choices=[('Nizak', 'Nizak'), ('Srednji', 'Srednji'), ('Visok', 'Visok')], default='Srednji', max_length=20)),
                ('task_status', models.CharField(choices=[('Zadatak nije započet', 'Zadatak nije započet'), ('Zadatak se izvršava', 'Zadatak se izvršava'), ('Zadatak je završen', 'Zadatak je završen')], default='Zadatak nije započet', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
